### ISSUE TITLE
Make scythes not use durability when cutting grass

### ISSUE THREAD

**Issue by Jackiecrazy** [Ladysnake/Dissolution#39]
I poked through the Git a bit to see how to implement wider sweeps with the ItemSword, and one thing that struck me was that rather than using per-player trackers for the scythe you were using a variable in a singleton class, so it seems to me that at any given time only one person can swing an iron scythe or lurking scythe, which kinda sounds a bit server-unfriendly. Maybe an update changed something, maybe you fixed it already, maybe I'm dumb and missed something, but just wanted to point that out. I'd fix up something but I'm already neck deep in my own projects, sorry ._. On the same note, it would be nice if scythes cut grass in an AoE fashion without using durability and leaves by using durability (since there's the extra, imaginary branches to cut through).

**Comment by Pyrofab** [comment]
If you are talking about the boolean `isRunningAOE`, this boolean is set at the beginning of the method and reverted at the end of it. This code runs exclusively on the server side, which means no multithreading. Since there is no multithreading, players cannot attack simultaneously, even if they strike in the same tick, the game will run one attack after the other. So there is theoretically no way it could cause issues.

**Comment by Pyrofab** [comment]
Issue technically solved now that Scythes have been removed. They will come back in another mod, eventually.
