### ISSUE TITLE
PlayerRevive incompatibility

### ISSUE THREAD

**Issue by CreativeMD** [Ladysnake/Dissolution#71]
Hey there,
I'm the author of PlayerRevive, a mod which prevents death, instead the player will be knocked down. A timer will start, within this time the player can be revived otherwise he/ she will die. Unfortunately there seems to be an issue with Dissolution, someone reported it recently (https://github.com/CreativeMD/PlayerRevive/issues/21). I'm confused by the crash-report as it crash during iterating all players ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.12/src/main/java/com/creativemd/playerrevive/server/ReviveEventServer.java#L76)).

Maybe you have an idea how to make both mods compatible?

In Regards
CreativeMD

**Comment by Pyrofab** [comment]
I also got that issue reported, but I don't really know what happens. It only occurs when the option to skip the death screen is enabled, so the issue is probably in [this code, mostly copypasted from vanilla](https://github.com/Ladysnake/Dissolution/blob/1.12.2/src/main/java/ladysnake/dissolution/common/handlers/PlayerRespawnHandler.java#L174-L336). I would guess there is some weirdness involved with vanilla not handling properly players respawning in the same tick.

**Comment by CreativeMD** [comment]
Ok, I will test if catching the exception will fix the issue.

**Comment by CreativeMD** [comment]
Never mind I found an even better way to fix it. I just use the PlayerTickEvent instead (no idea why I was not using it in the first place). I'm pretty sure it should be fixed now. Thanks for your help!

**Comment by Pyrofab** [comment]
My pleasure to help squashing this bug
